### ISSUE TITLE
Eslint configuration throwing 'React' must be in scope when using JSX error on React V17 Application

### ISSUE THREAD

**Issue by bhattaraib58** [leapfrogtechnology/eslint-config-leapfrog#11]
With React v17,  `import React from 'react';` is not needed to be in scope.
When linting the code on  "eslint-config-leapfrog/react", configuration. 'React' must be in scope when using JSX  error is thrown.

Steps to reproduce:
- Create new v17 app with CRA `npx create-react-app my-app`
- Add leapfrog react configuration,  "eslint-config-leapfrog/react", 
- Lint the code using `eslint src`
- You should get the 'React' must be in scope when using JSX error

**Comment by mesaugat** [comment]
We have no intention to make changes to this package. Closing!
